### ISSUE TITLE
Please Don't use Virustotal when testing for a WD bypass

### ISSUE THREAD

**Issue by abdou11ddq** [CYBERDEVILZ/Cryptonite#58]
Hello, I saw you're struggling with wanting to code a script to bypass Windows defender, I don't know as much as you but trough my knowledge I know that Virustotal is a death wish to test a Malware, So please don't test on it you're script could get undetected at the first time but the second will get detected, instead you can use something like "Nodistribute (it's dead along time ago, just for info) " or "antiscan.me"

as I said I'm not as experience as you but I hope this little information is helpful

**Comment by CYBERDEVILZ** [comment]
@abdou11ddq 
I know right!? One of the main reasons why the moment a FUD script created by someone becomes useless is because they make them public and most of the people test this on VT. VT is such a scam. They literally sell the signature to other antivirus developers potentially crushing the time and the painful effort put by the FUD creator. 

Anyways, I am trying my hands on other methods at present. A lot of them has become unsuccessful but I ain't backing down!
